# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 142a68209e04ea21bc96afdfb9ea594f44c7a7e8299a878275c39994450afb58148c817c7d1a2a3194367c8bc5ef362fc63d6c67ef2ef3728df0b7efa2536817

test:
  secret_key_base: 3d8450978895ab2d2db79bced52a99668da38eb65ad12282c05acd583195e810e81bd49b9fd20137a85a538b0bf27892b92e682f409cf5429cfa7cb77a3874bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
